"Resource/UI/ClassMenu.res"
{
	"class"
	{
		ControlName	"CClassMenu"
		fieldName	"class"
		xpos	"76"
		ypos	"0"
		wide	"552"
		tall	"448"
		autoResize	"0"
		pinCorner	"0"
		visible	"1"
		enabled	"1"
		tabPosition	"0"
	}

	"joinClass"
	{
		ControlName	"Label"
		fieldName	"joinClass"
		xpos	"8"
		ypos	"72"
		wide	"160"
		tall	"24"
		autoResize	"0"
		pinCorner	"0"
		visible	"1"
		enabled	"1"
		labelText	"#FF_CHANGECLASS"
		textAlignment	"west"
		dulltext	"0"
		brighttext	"1"
		"font"		"MenuTitle"
	}

	"classInfoLabel"
	{
		ControlName	"Label"
		fieldName	"classInfoLabel"
		xpos	"168"
		ypos	"72"
		wide	"180"
		tall	"24"
		autoResize	"0"
		pinCorner	"0"
		visible	"0"
		enabled	"1"
		labelText	"#Valve_Class_Info"
		textAlignment	"west"
		dulltext	"0"
		brighttext	"1"
	}

	"ClassInfo"
	{
		ControlName	"Panel"
		fieldName	"ClassInfo"
		xpos	"168"
		ypos	"116"
		wide	"400"
		tall	"380"
		autoResize	"3"
		pinCorner	"0"
		visible	"0"
		enabled	"0"
		tabPosition	"0"
	}

	"ScoutButton"
	{
		"ControlName"		"Button"
		"fieldName"			"ScoutButton"
		"xpos"				"76"
		"ypos"				"116"
		"wide"				"68"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"3"
		"labelText"			"#FF_MENU_SCOUT"
		"font"				"ClassMenu"
		"textAlignment"		"west"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"class scout"
	}
	"SniperButton"
	{
		"ControlName"		"Button"
		"fieldName"			"SniperButton"
		"xpos"				"156"
		"ypos"				"116"
		"wide"				"68"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"4"
		"labelText"			"#FF_MENU_SNIPER"
		"font"				"ClassMenu"
		"textAlignment"		"west"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"class sniper"
	}

	"SoldierButton"
	{
		"ControlName"		"Button"
		"fieldName"			"SoldierButton"
		"xpos"				"76"
		"ypos"				"148"
		"wide"				"68"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"5"
		"labelText"			"#FF_MENU_SOLDIER"
		"font"				"ClassMenu"
		"textAlignment"		"west"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"class soldier"
	}
	
	"DemomanButton"
	{
		"ControlName"		"Button"
		"fieldName"			"DemomanButton"
		"xpos"				"156"
		"ypos"				"148"
		"wide"				"68"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"1"
		"labelText"			"#FF_MENU_DEMOMAN"
		"font"				"ClassMenu"
		"textAlignment"		"west"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"class demoman"
	}
	"MedicButton"
	{
		"ControlName"		"Button"
		"fieldName"			"MedicButton"
		"xpos"				"76"
		"ypos"				"180"
		"wide"				"68"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"2"
		"labelText"			"#FF_MENU_MEDIC"
		"font"				"ClassMenu"
		"textAlignment"		"west"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"class medic"
	}
	"HwguyButton"
	{
		"ControlName"		"Button"
		"fieldName"			"HwguyButton"
		"xpos"				"156"
		"ypos"				"180"
		"wide"				"68"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"#FF_MENU_HWGUY"
		"font"				"ClassMenu"
		"textAlignment"		"west"
		"dulltext"			"0"
		"brighttext"		"0"
		"Command"			"class hwguy"
	}
	"PyroButton"
	{
		"ControlName"		"Button"
		"fieldName"			"PyroButton"
		"xpos"				"76"
		"ypos"				"212"
		"wide"				"68"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"#FF_MENU_PYRO"
		"font"				"ClassMenu"
		"textAlignment"		"west"
		"dulltext"			"0"
		"brighttext"		"0"
		"Command"			"class pyro"
	}
	"SpyButton"
	{
		"ControlName"		"Button"
		"fieldName"			"SpyButton"
		"xpos"				"156"
		"ypos"				"212"
		"wide"				"68"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"#FF_MENU_SPY"
		"font"				"ClassMenu"
		"textAlignment"		"west"
		"dulltext"			"0"
		"brighttext"		"0"
		"Command"			"class spy"
	}
	"EngineerButton"
	{
		"ControlName"		"Button"
		"fieldName"			"EngineerButton"
		"xpos"				"76"
		"ypos"				"244"
		"wide"				"68"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"#FF_MENU_ENGINEER"
		"font"				"ClassMenu"
		"textAlignment"		"west"
		"dulltext"			"0"
		"brighttext"		"0"
		"Command"			"class engineer"
	}
	"CivilianButton"
	{
		"ControlName"		"Button"
		"fieldName"			"CivilianButton"
		"xpos"				"156"
		"ypos"				"244"
		"wide"				"68"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"#FF_MENU_CIVILIAN"
		"font"				"ClassMenu"
		"textAlignment"		"west"
		"dulltext"			"0"
		"brighttext"		"0"
		"Command"			"class civilian"
	}
	"RandomButton"
	{
		"ControlName"		"Button"
		"fieldName"			"RandomButton"
		"xpos"				"76"
		"ypos"				"276"
		"wide"				"148"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"#FF_MENU_RANDOM"
		"font"				"ClassMenu"
		"textAlignment"		"west"
		"dulltext"			"0"
		"brighttext"		"0"
		"Command"			"class random"
	}
	"CancelButton"
	{
		ControlName	"Button"
		fieldName	"CancelButton"
		xpos	"0"
		ypos	"308"
		wide	"148"
		tall	"20"
		autoResize	"0"
		pinCorner	"2"
		visible	"1"
		enabled	"1"
		tabPosition	"0"
		labelText	"#FF_MENU_CANCEL"
		textAlignment	"west"
		dulltext	"0"
		brighttext	"0"
		Command	"vguicancel"
	}
}
