"resource/ui/FFCustomHudOptionsPanelStyleHeaderText.res"
{
	"HeaderText"
	{
		"ControlName"		"PropertyPage"
		"fieldName"		"HeaderText"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"614"
		"tall"		"318"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextColor"
	{
		"ControlName"		"FFColorPicker"
		"fieldName"		"HeaderTextColor"
		"xpos"		"515"
		"ypos"		"215"
		"wide"		"50"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextColorRed"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderTextColorRed"
		"xpos"		"500"
		"ypos"		"70"
		"wide"		"75"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextColorRedInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderTextColorRedInput"
		"xpos"		"570"
		"ypos"		"70"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderTextColorGreen"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderTextColorGreen"
		"xpos"		"500"
		"ypos"		"95"
		"wide"		"75"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextColorGreenInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderTextColorGreenInput"
		"xpos"		"570"
		"ypos"		"95"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderTextColorBlue"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderTextColorBlue"
		"xpos"		"500"
		"ypos"		"120"
		"wide"		"75"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextColorBlueInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderTextColorBlueInput"
		"xpos"		"570"
		"ypos"		"120"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderTextColorAlpha"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderTextColorAlpha"
		"xpos"		"500"
		"ypos"		"145"
		"wide"		"75"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextColorAlphaInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderTextColorAlphaInput"
		"xpos"		"570"
		"ypos"		"145"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderTextColorColorMode"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HeaderTextColorColorMode"
		"xpos"		"450"
		"ypos"		"40"
		"wide"		"150"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"HeaderTextColorBackground"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HeaderTextColorBackground"
		"xpos"		"475"
		"ypos"		"175"
		"zpos"		"-1"
		"wide"		"128"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"		"crosshairbg"
		"border"		"DepressedBorder"
		"scaleImage"		"0"
	}
	"headerTextSize"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderTextSize"
		"xpos"		"270"
		"ypos"		"85"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextSizeInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderTextSizeInput"
		"xpos"		"365"
		"ypos"		"85"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderTextX"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderTextX"
		"xpos"		"270"
		"ypos"		"225"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextXInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderTextXInput"
		"xpos"		"365"
		"ypos"		"225"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderTextY"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderTextY"
		"xpos"		"270"
		"ypos"		"250"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextYInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderTextYInput"
		"xpos"		"365"
		"ypos"		"250"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderTextAnchorPositionTopLeft"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderTextAnchorPositionTopLeft"
		"xpos"		"45"
		"ypos"		"80"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderTextAnchorPositionTopCenter"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderTextAnchorPositionTopCenter"
		"xpos"		"95"
		"ypos"		"80"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderTextAnchorPositionTopRight"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderTextAnchorPositionTopRight"
		"xpos"		"145"
		"ypos"		"80"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderTextAnchorPositionMiddleLeft"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderTextAnchorPositionMiddleLeft"
		"xpos"		"45"
		"ypos"		"100"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderTextAnchorPositionMiddleCenter"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderTextAnchorPositionMiddleCenter"
		"xpos"		"95"
		"ypos"		"100"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderTextAnchorPositionMiddleRight"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderTextAnchorPositionMiddleRight"
		"xpos"		"145"
		"ypos"		"100"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderTextAnchorPositionBottomLeft"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderTextAnchorPositionBottomLeft"
		"xpos"		"45"
		"ypos"		"120"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderTextAnchorPositionBottomCenter"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderTextAnchorPositionBottomCenter"
		"xpos"		"95"
		"ypos"		"120"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderTextAnchorPositionBottomRight"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderTextAnchorPositionBottomRight"
		"xpos"		"145"
		"ypos"		"120"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderTextAlignHorizontallyCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HeaderTextAlignHorizontallyCombo"
		"xpos"		"115"
		"ypos"		"225"
		"wide"		"75"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"HeaderTextAlignVerticallyCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HeaderTextAlignVerticallyCombo"
		"xpos"		"115"
		"ypos"		"250"
		"wide"		"75"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"showHeaderText"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ShowHeaderText"
		"xpos"		"5"
		"ypos"		"5"
		"wide"		"140"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Show"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"headerTextShadow"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderTextShadow"
		"xpos"		"260"
		"ypos"		"115"
		"wide"		"140"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_DropShadow"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderTextAnchorPositionTopDiv"
	{
		"ControlName"		"Divider"
		"fieldName"		"HeaderTextAnchorPositionTopDiv"
		"xpos"		"63"
		"ypos"		"88"
		"wide"		"90"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextAnchorPositionLeftDiv"
	{
		"ControlName"		"Divider"
		"fieldName"		"HeaderTextAnchorPositionLeftDiv"
		"xpos"		"57"
		"ypos"		"94"
		"wide"		"2"
		"tall"		"30"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextAnchorPositionBottomDiv"
	{
		"ControlName"		"Divider"
		"fieldName"		"HeaderTextAnchorPositionBottomDiv"
		"xpos"		"63"
		"ypos"		"128"
		"wide"		"90"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextAnchorPositionRightDiv"
	{
		"ControlName"		"Divider"
		"fieldName"		"HeaderTextAnchorPositionRightDiv"
		"xpos"		"157"
		"ypos"		"94"
		"wide"		"2"
		"tall"		"30"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextColorRedLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderTextColorRedLabel"
		"xpos"		"425"
		"ypos"		"70"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Red"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderTextColorGreenLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderTextColorGreenLabel"
		"xpos"		"425"
		"ypos"		"95"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Green"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderTextColorBlueLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderTextColorBlueLabel"
		"xpos"		"425"
		"ypos"		"120"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Blue"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderTextColorAlphaLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderTextColorAlphaLabel"
		"xpos"		"425"
		"ypos"		"145"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Alpha"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderTextColorModeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderTextColorModeLabel"
		"xpos"		"450"
		"ypos"		"20"
		"wide"		"150"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_ColorMode"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderTextXLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderTextXLabel"
		"xpos"		"215"
		"ypos"		"225"
		"wide"		"50"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_X"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider1"
		"xpos"		"410"
		"ypos"		"10"
		"wide"		"2"
		"tall"		"300"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Divider4"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider4"
		"xpos"		"205"
		"ypos"		"10"
		"wide"		"2"
		"tall"		"300"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderTextYLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderTextYLabel"
		"xpos"		"215"
		"ypos"		"250"
		"wide"		"50"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Y"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderTextSizeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderTextSizeLabel"
		"xpos"		"215"
		"ypos"		"85"
		"wide"		"50"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Size"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"TextLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextLabel"
		"xpos"		"215"
		"ypos"		"55"
		"wide"		"185"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AnchorPositionLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AnchorPositionLabel"
		"xpos"		"10"
		"ypos"		"55"
		"wide"		"185"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_AnchorPosition"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AlignmentLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlignmentLabel"
		"xpos"		"10"
		"ypos"		"195"
		"wide"		"185"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Alignment"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"PositionOffsetLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PositionOffsetLabel"
		"xpos"		"215"
		"ypos"		"195"
		"wide"		"190"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_PositionOffset"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AlignHorizontallyLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlignHorizontallyLabel"
		"xpos"		"10"
		"ypos"		"225"
		"wide"		"100"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Horizontal"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AlignVerticallyLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlignVerticallyLabel"
		"xpos"		"10"
		"ypos"		"250"
		"wide"		"100"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Vertical"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"1125"
		"ypos"		"263"
		"wide"		"300"
		"tall"		"419"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
