"resource/ui/FFOptionsSubCustomHudPositionPresets.res"
{
	"CustomHudPositionPresets"
	{
		"ControlName"		"CFFCustomHudPositionPresets"
		"fieldName"		"CustomHudPositionPresets"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"615"
		"tall"		"277"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"PositionPresetSelectionCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"PositionPresetSelectionCombo"
		"xpos"		"5"
		"ypos"		"5"
		"wide"		"210"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"NewPresetButton"
	{
		"ControlName"		"Button"
		"fieldName"		"NewPresetButton"
		"xpos"		"220"
		"ypos"		"5"
		"wide"		"90"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_New"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"NewPreset"
		"Default"		"0"
	}
	"CopyPresetButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CopyPresetButton"
		"xpos"		"315"
		"ypos"		"5"
		"wide"		"90"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Copy"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"CopyPreset"
		"Default"		"0"
	}
	"DeletePresetButton"
	{
		"ControlName"		"Button"
		"fieldName"		"DeletePresetButton"
		"xpos"		"410"
		"ypos"		"5"
		"wide"		"90"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Delete"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"DeletePreset"
		"Default"		"0"
	}
	"RenamePresetButton"
	{
		"ControlName"		"Button"
		"fieldName"		"RenamePresetButton"
		"xpos"		"505"
		"ypos"		"5"
		"wide"		"90"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Rename"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"RenamePreset"
		"Default"		"0"
	}
	"AlignHorizontallyCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"AlignHorizontallyCombo"
		"xpos"		"130"
		"ypos"		"135"
		"wide"		"75"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"AlignVerticallyCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"AlignVerticallyCombo"
		"xpos"		"130"
		"ypos"		"160"
		"wide"		"75"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"x"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"X"
		"xpos"		"100"
		"ypos"		"60"
		"wide"		"250"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"XInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"XInput"
		"xpos"		"345"
		"ypos"		"60"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"Y"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"Y"
		"xpos"		"100"
		"ypos"		"85"
		"wide"		"250"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"YInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"YInput"
		"xpos"		"345"
		"ypos"		"85"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"AlphaLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlphaLabel"
		"xpos"		"986"
		"ypos"		"250"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Alpha"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"PanelRedLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PanelRedLabel"
		"xpos"		"430"
		"ypos"		"190"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Red"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"PanelGreenLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PanelGreenLabel"
		"xpos"		"430"
		"ypos"		"165"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Green"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"PanelBlueLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PanelBlueLabel"
		"xpos"		"430"
		"ypos"		"215"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Blue"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"PanelAlphaLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PanelAlphaLabel"
		"xpos"		"1532"
		"ypos"		"240"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"1"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Alpha"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"XLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"XLabel"
		"xpos"		"65"
		"ypos"		"60"
		"wide"		"30"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_X"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"YLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"YLabel"
		"xpos"		"65"
		"ypos"		"85"
		"wide"		"30"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Y"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"PositioningLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PositioningLabel"
		"xpos"		"10"
		"ypos"		"35"
		"wide"		"150"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Positioning"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AlignmentLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlignmentLabel"
		"xpos"		"10"
		"ypos"		"115"
		"wide"		"150"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Alignment"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AlignHorizontallyLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlignHorizontallyLabel"
		"xpos"		"15"
		"ypos"		"135"
		"wide"		"110"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Horizontal"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AlignVerticallyLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlignVerticallyLabel"
		"xpos"		"15"
		"ypos"		"160"
		"wide"		"110"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Vertical"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"501"
		"ypos"		"180"
		"wide"		"300"
		"tall"		"420"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
