"resource/ui/FFCustomHudOptionsPanelStylePanel.res"
{
	"panel"
	{
		"ControlName"		"PropertyPage"
		"fieldName"		"Panel"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"614"
		"tall"		"318"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"PanelColor"
	{
		"ControlName"		"FFColorPicker"
		"fieldName"		"PanelColor"
		"xpos"		"275"
		"ypos"		"175"
		"wide"		"50"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"PanelColorRed"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"PanelColorRed"
		"xpos"		"95"
		"ypos"		"165"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"PanelColorRedInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"PanelColorRedInput"
		"xpos"		"185"
		"ypos"		"165"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"PanelColorGreen"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"PanelColorGreen"
		"xpos"		"95"
		"ypos"		"190"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"PanelColorGreenInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"PanelColorGreenInput"
		"xpos"		"185"
		"ypos"		"190"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"PanelColorBlue"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"PanelColorBlue"
		"xpos"		"95"
		"ypos"		"215"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"PanelColorBlueInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"PanelColorBlueInput"
		"xpos"		"185"
		"ypos"		"215"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"PanelColorAlpha"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"PanelColorAlpha"
		"xpos"		"95"
		"ypos"		"240"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"PanelColorAlphaInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"PanelColorAlphaInput"
		"xpos"		"185"
		"ypos"		"240"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"PanelColorColorMode"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"PanelColorColorMode"
		"xpos"		"65"
		"ypos"		"135"
		"wide"		"150"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"PanelColorBackground"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"PanelColorBackground"
		"xpos"		"235"
		"ypos"		"135"
		"zpos"		"-1"
		"wide"		"128"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"		"crosshairbg"
		"border"		"DepressedBorder"
		"scaleImage"		"0"
		"scaleAmount"		"0.000000"
		"tileImage"		"0"
		"tileHorizontally"		"0"
		"tileVertically"		"0"
	}
	"panelMargin"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"PanelMargin"
		"xpos"		"95"
		"ypos"		"60"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"PanelMarginInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"PanelMarginInput"
		"xpos"		"185"
		"ypos"		"60"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"PanelTypeCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"PanelTypeCombo"
		"xpos"		"65"
		"ypos"		"25"
		"wide"		"150"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"showPanel"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ShowPanel"
		"xpos"		"5"
		"ypos"		"5"
		"wide"		"140"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Show"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"PanelColorRedLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PanelColorRedLabel"
		"xpos"		"20"
		"ypos"		"165"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Red"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"PanelColorGreenLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PanelColorGreenLabel"
		"xpos"		"20"
		"ypos"		"190"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Green"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"PanelColorBlueLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PanelColorBlueLabel"
		"xpos"		"20"
		"ypos"		"215"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Blue"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"PanelColorAlphaLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PanelColorAlphaLabel"
		"xpos"		"20"
		"ypos"		"240"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"1"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Alpha"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"PanelColorModeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PanelColorModeLabel"
		"xpos"		"65"
		"ypos"		"115"
		"wide"		"150"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_ColorMode"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"PanelMarginLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PanelMarginLabel"
		"xpos"		"20"
		"ypos"		"60"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Margin"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"843"
		"ypos"		"126"
		"wide"		"300"
		"tall"		"420"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
