"resource/ui/FFCustomHudOptions.res"
{
	"FFCustomHudOptions"
	{
		"ControlName"		"CFFCustomHudOptionsPanel"
		"fieldName"		"FFCustomHudOptions"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"640"
		"tall"		"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#GameUI_CustomHudOptions"
	}
	"CustomHudPages"
	{
		"ControlName"		"PropertySheet"
		"fieldName"		"CustomHudPages"
		"xpos"		"8"
		"ypos"		"32"
		"wide"		"624"
		"tall"		"414"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"OKButton"
	{
		"ControlName"		"Button"
		"fieldName"		"OKButton"
		"xpos"		"394"
		"ypos"		"452"
		"wide"		"72"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_OK"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"OK"
	}
	"CancelButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CancelButton"
		"xpos"		"475"
		"ypos"		"452"
		"wide"		"72"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Cancel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"Cancel"
	}
	"ApplyButton"
	{
		"ControlName"		"Button"
		"fieldName"		"ApplyButton"
		"xpos"		"555"
		"ypos"		"452"
		"wide"		"72"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Apply"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"Apply"
	}
}
