"resource/ui/FFCustomHudOptionsPanelStylePresets.res"
{
	"CustomHudPanelStylePresets"
	{
		"ControlName"		"CFFCustomHudPanelStylePresets"
		"fieldName"		"CustomHudPanelStylePresets"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"624"
		"tall"		"386"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"PanelStylePresetSelectionCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"PanelStylePresetSelectionCombo"
		"xpos"		"5"
		"ypos"		"5"
		"wide"		"210"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"NewPresetButton"
	{
		"ControlName"		"Button"
		"fieldName"		"NewPresetButton"
		"xpos"		"220"
		"ypos"		"5"
		"wide"		"90"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_New"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"NewPreset"
		"Default"		"0"
	}
	"CopyPresetButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CopyPresetButton"
		"xpos"		"315"
		"ypos"		"5"
		"wide"		"90"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Copy"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"CopyPreset"
		"Default"		"0"
	}
	"DeletePresetButton"
	{
		"ControlName"		"Button"
		"fieldName"		"DeletePresetButton"
		"xpos"		"410"
		"ypos"		"5"
		"wide"		"90"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Delete"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"DeletePreset"
		"Default"		"0"
	}
	"RenamePresetButton"
	{
		"ControlName"		"Button"
		"fieldName"		"RenamePresetButton"
		"xpos"		"505"
		"ypos"		"5"
		"wide"		"90"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Rename"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"RenamePreset"
		"Default"		"0"
	}
	"HeaderText"
	{
		"ControlName"		"PropertyPage"
		"fieldName"		"HeaderText"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"614"
		"tall"		"318"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIcon"
	{
		"ControlName"		"PropertyPage"
		"fieldName"		"HeaderIcon"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"614"
		"tall"		"318"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"text"
	{
		"ControlName"		"PropertyPage"
		"fieldName"		"Text"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"614"
		"tall"		"318"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"panel"
	{
		"ControlName"		"PropertyPage"
		"fieldName"		"Panel"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"614"
		"tall"		"318"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"PanelStylePages"
	{
		"ControlName"		"PropertySheet"
		"fieldName"		"PanelStylePages"
		"xpos"		"5"
		"ypos"		"35"
		"wide"		"614"
		"tall"		"346"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"1225"
		"ypos"		"358"
		"wide"		"300"
		"tall"		"419"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
