"resource/ui/FFCustomHudOptionsPanelStyleText.res"
{
	"text"
	{
		"ControlName"		"PropertyPage"
		"fieldName"		"Text"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"614"
		"tall"		"318"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextColor"
	{
		"ControlName"		"FFColorPicker"
		"fieldName"		"TextColor"
		"xpos"		"515"
		"ypos"		"215"
		"wide"		"50"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextColorRed"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"TextColorRed"
		"xpos"		"500"
		"ypos"		"70"
		"wide"		"75"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextColorRedInput"
	{
		"ControlName"		"CLinkedTextEntry"
		"fieldName"		"TextColorRedInput"
		"xpos"		"570"
		"ypos"		"70"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"TextColorGreen"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"TextColorGreen"
		"xpos"		"500"
		"ypos"		"95"
		"wide"		"75"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextColorGreenInput"
	{
		"ControlName"		"CLinkedTextEntry"
		"fieldName"		"TextColorGreenInput"
		"xpos"		"570"
		"ypos"		"95"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"TextColorBlue"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"TextColorBlue"
		"xpos"		"500"
		"ypos"		"120"
		"wide"		"75"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextColorBlueInput"
	{
		"ControlName"		"CLinkedTextEntry"
		"fieldName"		"TextColorBlueInput"
		"xpos"		"570"
		"ypos"		"120"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"TextColorAlpha"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"TextColorAlpha"
		"xpos"		"500"
		"ypos"		"145"
		"wide"		"75"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextColorAlphaInput"
	{
		"ControlName"		"CLinkedTextEntry"
		"fieldName"		"TextColorAlphaInput"
		"xpos"		"570"
		"ypos"		"145"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"TextColorColorMode"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"TextColorColorMode"
		"xpos"		"450"
		"ypos"		"40"
		"wide"		"150"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"TextColorBackground"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"TextColorBackground"
		"xpos"		"475"
		"ypos"		"175"
		"zpos"		"-1"
		"wide"		"128"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"		"crosshairbg"
		"scaleImage"		"0"
	}
	"TextSize"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"TextSize"
		"xpos"		"270"
		"ypos"		"85"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextSizeInput"
	{
		"ControlName"		"CLinkedTextEntry"
		"fieldName"		"TextSizeInput"
		"xpos"		"365"
		"ypos"		"85"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"TextX"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"TextX"
		"xpos"		"275"
		"ypos"		"225"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextXInput"
	{
		"ControlName"		"CLinkedTextEntry"
		"fieldName"		"TextXInput"
		"xpos"		"365"
		"ypos"		"225"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"TextY"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"TextY"
		"xpos"		"275"
		"ypos"		"250"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextYInput"
	{
		"ControlName"		"CLinkedTextEntry"
		"fieldName"		"TextYInput"
		"xpos"		"365"
		"ypos"		"250"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"TextAnchorPositionTopLeft"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"TextAnchorPositionTopLeft"
		"xpos"		"45"
		"ypos"		"81"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"TextAnchorPositionTopCenter"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"TextAnchorPositionTopCenter"
		"xpos"		"95"
		"ypos"		"81"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"TextAnchorPositionTopRight"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"TextAnchorPositionTopRight"
		"xpos"		"145"
		"ypos"		"81"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"TextAnchorPositionMiddleLeft"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"TextAnchorPositionMiddleLeft"
		"xpos"		"45"
		"ypos"		"101"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"TextAnchorPositionMiddleCenter"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"TextAnchorPositionMiddleCenter"
		"xpos"		"95"
		"ypos"		"101"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"TextAnchorPositionMiddleRight"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"TextAnchorPositionMiddleRight"
		"xpos"		"145"
		"ypos"		"101"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"TextAnchorPositionBottomLeft"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"TextAnchorPositionBottomLeft"
		"xpos"		"45"
		"ypos"		"121"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"TextAnchorPositionBottomCenter"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"TextAnchorPositionBottomCenter"
		"xpos"		"95"
		"ypos"		"121"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"TextAnchorPositionBottomRight"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"TextAnchorPositionBottomRight"
		"xpos"		"145"
		"ypos"		"121"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"TextAlignHorizontallyCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"TextAlignHorizontallyCombo"
		"xpos"		"115"
		"ypos"		"225"
		"wide"		"75"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"TextAlignVerticallyCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"TextAlignVerticallyCombo"
		"xpos"		"115"
		"ypos"		"250"
		"wide"		"75"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"TextShadow"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"TextShadow"
		"xpos"		"260"
		"ypos"		"115"
		"wide"		"140"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_DropShadow"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"TextColorRedLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextColorRedLabel"
		"xpos"		"425"
		"ypos"		"70"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Red"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"TextColorGreenLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextColorGreenLabel"
		"xpos"		"425"
		"ypos"		"95"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Green"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"TextColorBlueLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextColorBlueLabel"
		"xpos"		"425"
		"ypos"		"120"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Blue"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"TextColorAlphaLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextColorAlphaLabel"
		"xpos"		"425"
		"ypos"		"145"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Alpha"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"TextColorModeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextColorModeLabel"
		"xpos"		"450"
		"ypos"		"20"
		"wide"		"150"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_ColorMode"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"TextXLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextXLabel"
		"xpos"		"215"
		"ypos"		"225"
		"wide"		"50"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_X"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"TextYLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextYLabel"
		"xpos"		"215"
		"ypos"		"250"
		"wide"		"50"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Y"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"TextSizeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextSizeLabel"
		"xpos"		"215"
		"ypos"		"85"
		"wide"		"50"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Size"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"TextLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextLabel"
		"xpos"		"215"
		"ypos"		"55"
		"wide"		"185"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AnchorPositionLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AnchorPositionLabel"
		"xpos"		"10"
		"ypos"		"55"
		"wide"		"185"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_AnchorPosition"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"TextAnchorPositionTopDiv"
	{
		"ControlName"		"Divider"
		"fieldName"		"TextAnchorPositionTopDiv"
		"xpos"		"63"
		"ypos"		"89"
		"wide"		"90"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider1"
		"xpos"		"410"
		"ypos"		"10"
		"wide"		"2"
		"tall"		"300"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Divider4"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider4"
		"xpos"		"205"
		"ypos"		"10"
		"wide"		"2"
		"tall"		"300"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextAnchorPositionLeftDiv"
	{
		"ControlName"		"Divider"
		"fieldName"		"TextAnchorPositionLeftDiv"
		"xpos"		"57"
		"ypos"		"95"
		"wide"		"2"
		"tall"		"30"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextAnchorPositionBottomDiv"
	{
		"ControlName"		"Divider"
		"fieldName"		"TextAnchorPositionBottomDiv"
		"xpos"		"63"
		"ypos"		"129"
		"wide"		"90"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextAnchorPositionRightDiv"
	{
		"ControlName"		"Divider"
		"fieldName"		"TextAnchorPositionRightDiv"
		"xpos"		"157"
		"ypos"		"95"
		"wide"		"2"
		"tall"		"30"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"AlignmentLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlignmentLabel"
		"xpos"		"10"
		"ypos"		"195"
		"wide"		"185"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Alignment"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"PositionOffsetLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PositionOffsetLabel"
		"xpos"		"215"
		"ypos"		"195"
		"wide"		"185"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_PositionOffset"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AlignHorizontallyLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlignHorizontallyLabel"
		"xpos"		"10"
		"ypos"		"225"
		"wide"		"100"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Horizontal"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AlignVerticallyLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlignVerticallyLabel"
		"xpos"		"10"
		"ypos"		"250"
		"wide"		"100"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Vertical"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"1125"
		"ypos"		"263"
		"wide"		"300"
		"tall"		"419"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
