"resource/ui/FFCustomHudOptionsPanelStyleHeaderIcon.res"
{
	"HeaderIcon"
	{
		"ControlName"		"PropertyPage"
		"fieldName"		"HeaderIcon"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"614"
		"tall"		"318"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconColor"
	{
		"ControlName"		"FFColorPicker"
		"fieldName"		"HeaderIconColor"
		"xpos"		"515"
		"ypos"		"215"
		"wide"		"50"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconColorRed"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderIconColorRed"
		"xpos"		"500"
		"ypos"		"70"
		"wide"		"75"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconColorRedInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderIconColorRedInput"
		"xpos"		"570"
		"ypos"		"70"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderIconColorGreen"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderIconColorGreen"
		"xpos"		"500"
		"ypos"		"95"
		"wide"		"75"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconColorGreenInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderIconColorGreenInput"
		"xpos"		"570"
		"ypos"		"95"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderIconColorBlue"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderIconColorBlue"
		"xpos"		"500"
		"ypos"		"120"
		"wide"		"75"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconColorBlueInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderIconColorBlueInput"
		"xpos"		"570"
		"ypos"		"120"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderIconColorAlpha"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderIconColorAlpha"
		"xpos"		"500"
		"ypos"		"145"
		"wide"		"75"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconColorAlphaInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderIconColorAlphaInput"
		"xpos"		"570"
		"ypos"		"145"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderIconColorColorMode"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HeaderIconColorColorMode"
		"xpos"		"450"
		"ypos"		"40"
		"wide"		"150"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"HeaderIconColorBackground"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HeaderIconColorBackground"
		"xpos"		"475"
		"ypos"		"175"
		"zpos"		"-1"
		"wide"		"128"
		"tall"		"128"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"		"crosshairbg"
		"border"		"DepressedBorder"
		"scaleImage"		"0"
	}
	"HeaderIconSize"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderIconSize"
		"xpos"		"270"
		"ypos"		"85"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconSizeInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderIconSizeInput"
		"xpos"		"365"
		"ypos"		"85"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderIconX"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderIconX"
		"xpos"		"275"
		"ypos"		"225"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconXInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderIconXInput"
		"xpos"		"365"
		"ypos"		"225"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderIconY"
	{
		"ControlName"		"CFFInputSlider"
		"fieldName"		"HeaderIconY"
		"xpos"		"275"
		"ypos"		"250"
		"wide"		"95"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconYInput"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"HeaderIconYInput"
		"xpos"		"365"
		"ypos"		"250"
		"wide"		"32"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
		"unicode"		"0"
	}
	"HeaderIconAnchorPositionTopLeft"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderIconAnchorPositionTopLeft"
		"xpos"		"45"
		"ypos"		"80"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderIconAnchorPositionTopCenter"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderIconAnchorPositionTopCenter"
		"xpos"		"95"
		"ypos"		"80"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderIconAnchorPositionTopRight"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderIconAnchorPositionTopRight"
		"xpos"		"145"
		"ypos"		"80"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderIconAnchorPositionMiddleLeft"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderIconAnchorPositionMiddleLeft"
		"xpos"		"45"
		"ypos"		"100"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderIconAnchorPositionMiddleCenter"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderIconAnchorPositionMiddleCenter"
		"xpos"		"95"
		"ypos"		"100"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderIconAnchorPositionMiddleRight"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderIconAnchorPositionMiddleRight"
		"xpos"		"145"
		"ypos"		"100"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderIconAnchorPositionBottomLeft"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderIconAnchorPositionBottomLeft"
		"xpos"		"45"
		"ypos"		"120"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderIconAnchorPositionBottomCenter"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderIconAnchorPositionBottomCenter"
		"xpos"		"95"
		"ypos"		"120"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderIconAnchorPositionBottomRight"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderIconAnchorPositionBottomRight"
		"xpos"		"145"
		"ypos"		"120"
		"wide"		"26"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"CheckButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderIconAlignHorizontallyCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HeaderIconAlignHorizontallyCombo"
		"xpos"		"115"
		"ypos"		"225"
		"wide"		"75"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"HeaderIconAlignVerticallyCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HeaderIconAlignVerticallyCombo"
		"xpos"		"115"
		"ypos"		"250"
		"wide"		"75"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"showHeaderIcon"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ShowHeaderIcon"
		"xpos"		"5"
		"ypos"		"5"
		"wide"		"140"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Show"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderIconShadow"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HeaderIconShadow"
		"xpos"		"260"
		"ypos"		"115"
		"wide"		"140"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_DropShadow"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"HeaderIconColorRedLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderIconColorRedLabel"
		"xpos"		"425"
		"ypos"		"70"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Red"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderIconColorGreenLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderIconColorGreenLabel"
		"xpos"		"425"
		"ypos"		"95"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Green"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderIconColorBlueLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderIconColorBlueLabel"
		"xpos"		"425"
		"ypos"		"120"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Blue"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderIconColorAlphaLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderIconColorAlphaLabel"
		"xpos"		"425"
		"ypos"		"145"
		"wide"		"70"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Alpha"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderIconColorModeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderIconColorModeLabel"
		"xpos"		"450"
		"ypos"		"20"
		"wide"		"150"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_ColorMode"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderIconColorPreview"
	{
		"ControlName"		"Panel"
		"fieldName"		"HeaderIconColorPreview"
		"xpos"		"360"
		"ypos"		"90"
		"wide"		"50"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconXLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderIconXLabel"
		"xpos"		"215"
		"ypos"		"225"
		"wide"		"50"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_X"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderIconYLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderIconYLabel"
		"xpos"		"215"
		"ypos"		"250"
		"wide"		"50"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Y"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderIconSizeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeaderIconSizeLabel"
		"xpos"		"215"
		"ypos"		"85"
		"wide"		"50"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Size"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider1"
		"xpos"		"410"
		"ypos"		"10"
		"wide"		"2"
		"tall"		"300"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Divider4"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider4"
		"xpos"		"205"
		"ypos"		"10"
		"wide"		"2"
		"tall"		"300"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TextLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextLabel"
		"xpos"		"215"
		"ypos"		"55"
		"wide"		"185"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AnchorPositionLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AnchorPositionLabel"
		"xpos"		"10"
		"ypos"		"55"
		"wide"		"185"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_AnchorPosition"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HeaderIconAnchorPositionTopDiv"
	{
		"ControlName"		"Divider"
		"fieldName"		"HeaderIconAnchorPositionTopDiv"
		"xpos"		"63"
		"ypos"		"88"
		"wide"		"90"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconAnchorPositionLeftDiv"
	{
		"ControlName"		"Divider"
		"fieldName"		"HeaderIconAnchorPositionLeftDiv"
		"xpos"		"57"
		"ypos"		"94"
		"wide"		"2"
		"tall"		"30"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconAnchorPositionBottomDiv"
	{
		"ControlName"		"Divider"
		"fieldName"		"HeaderIconAnchorPositionBottomDiv"
		"xpos"		"63"
		"ypos"		"128"
		"wide"		"90"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"HeaderIconAnchorPositionRightDiv"
	{
		"ControlName"		"Divider"
		"fieldName"		"HeaderIconAnchorPositionRightDiv"
		"xpos"		"157"
		"ypos"		"94"
		"wide"		"2"
		"tall"		"30"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"AlignmentLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlignmentLabel"
		"xpos"		"10"
		"ypos"		"195"
		"wide"		"185"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Alignment"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AlignHorizontallyLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlignHorizontallyLabel"
		"xpos"		"10"
		"ypos"		"225"
		"wide"		"100"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Horizontal"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"AlignVerticallyLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AlignVerticallyLabel"
		"xpos"		"10"
		"ypos"		"250"
		"wide"		"100"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Vertical"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"PositionOffsetLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PositionOffsetLabel"
		"xpos"		"215"
		"ypos"		"195"
		"wide"		"185"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_PositionOffset"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"1125"
		"ypos"		"263"
		"wide"		"300"
		"tall"		"419"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
