"resource/ui/FFOptionsSubCustomHudAssignPresets.res"
{
	"CustomHudAssignPresets"
	{
		"ControlName"		"CFFCustomHudAssignPresets"
		"fieldName"		"CustomHudAssignPresets"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"615"
		"tall"		"348"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"PreviewMode"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"PreviewMode"
		"xpos"		"315"
		"ypos"		"5"
		"wide"		"200"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_PreviewMode"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"ParentCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ParentCombo"
		"xpos"		"5"
		"ypos"		"5"
		"wide"		"150"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ChildCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ChildCombo"
		"xpos"		"160"
		"ypos"		"5"
		"wide"		"150"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ItemStyleCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ItemStyleCombo"
		"xpos"		"145"
		"ypos"		"100"
		"wide"		"210"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"PanelStyleCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"PanelStyleCombo"
		"xpos"		"145"
		"ypos"		"70"
		"wide"		"210"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"PositionCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"PositionCombo"
		"xpos"		"145"
		"ypos"		"40"
		"wide"		"210"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"CopyDefaultPosition"
	{
		"ControlName"		"Button"
		"fieldName"		"CopyDefaultPosition"
		"xpos"		"485"
		"ypos"		"40"
		"wide"		"120"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_CopyDefault"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"CopyDefaultPosition"
		"Default"		"0"
	}
	"CopyDefaultPanelStyle"
	{
		"ControlName"		"Button"
		"fieldName"		"CopyDefaultPanelStyle"
		"xpos"		"485"
		"ypos"		"70"
		"wide"		"120"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_CopyDefault"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"CopyDefaultPanelStyle"
		"Default"		"0"
	}
	"CopyDefaultItemStyle"
	{
		"ControlName"		"Button"
		"fieldName"		"CopyDefaultItemStyle"
		"xpos"		"485"
		"ypos"		"100"
		"wide"		"120"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_CopyDefault"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"CopyDefaultItemStyle"
		"Default"		"0"
	}
	"SpecificOptions"
	{
		"ControlName"		"Panel"
		"fieldName"		"SpecificOptions"
		"xpos"		"10"
		"ypos"		"135"
		"wide"		"585"
		"tall"		"200"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"PanelStyleComboLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PanelStyleComboLabel"
		"xpos"		"5"
		"ypos"		"70"
		"wide"		"135"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_PanelStyle"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ItemStyleComboLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemStyleComboLabel"
		"xpos"		"5"
		"ypos"		"100"
		"wide"		"135"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_ItemStyle"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"PositionComboLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PositionComboLabel"
		"xpos"		"5"
		"ypos"		"40"
		"wide"		"135"
		"tall"		"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Position"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"710"
		"ypos"		"106"
		"wide"		"300"
		"tall"		"419"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
