"Resource/UI/TeamMenu.res"
{
	"team"
	{
		"ControlName"	"CTeamMenu"
		"fieldName"		"team"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"640"
		"tall"			"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"SysMenu"
	{
		"ControlName"	"Menu"
		"fieldName"		"SysMenu"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"64"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
	}
	"MapInfo"
	{
		"ControlName"	"RichText"
		"fieldName"		"MapInfo"
		"xpos"			"244"
		"ypos"			"116"
		"wide"			"316"
		"tall"			"286"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"joinTeam"
	{
		"ControlName"	"Label"
		"fieldName"		"joinTeam"
		"xpos"		"76"
		"ypos"		"22"
		"wide"		"450"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TITLE_TEAMSELECTION"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"TeamMenuTitles_large"
	}
	"mapname"
	{
		"ControlName"	"Label"
		"fieldName"		"mapname"
		"xpos"			"244"
		"ypos"			"72"
		"wide"			"180"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"1"
	}
	"BlueTeamButton"
	{
		"ControlName"	"Button"
		"fieldName"		"BlueTeamButton"
		"xpos"			"76"
		"ypos"			"116"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"font"			"TeamMenuTitles"
		"labelText"		"#FF_MENU_BLUE"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"team blue"
	}
	"RedTeamButton"
	{
		"ControlName"	"Button"
		"fieldName"		"RedTeamButton"
		"xpos"			"76"
		"ypos"			"148"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"font"			"TeamMenuTitles"
		"labelText"		"#FF_MENU_RED"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"team red"
	}
	"YellowTeamButton"
	{
		"ControlName"	"Button"
		"fieldName"		"YellowTeamButton"
		"xpos"			"76"
		"ypos"			"180"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
		"font"			"TeamMenuTitles"
		"labelText"		"#FF_MENU_YELLOW"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"team yellow"
	}
	"GreenTeamButton"
	{
		"ControlName"	"Button"
		"fieldName"		"GreenTeamButton"
		"xpos"			"76"
		"ypos"			"212"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
		"font"			"TeamMenuTitles"
		"labelText"		"#FF_MENU_GREEN"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"team green"
	}
	"AutoAssignButton"
	{
		"ControlName"	"Button"
		"fieldName"		"AutoAssignButton"
		"xpos"			"76"
		"ypos"			"244"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"font"			"TeamMenuTitles"
		"labelText"		"#FF_MENU_AUTOTEAM"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"team auto"
		"Default"		"1"
	}

	"SpectateButton"
	{
		"ControlName"	"Button"
		"fieldName"		"SpectateButton"
		"xpos"			"76"
		"ypos"			"276"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"font"			"TeamMenuTitles"
		"labelText"		"#FF_MENU_SPECTATOR"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"team spec"
	}
	"FlythroughButton"
	{
		"ControlName"	"Button"
		"fieldName"		"FlythroughButton"
		"xpos"			"76"
		"ypos"			"308"
		"wide"			"96"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"			"1"
		"enabled"		"1"
		"tabPosition"		"6"
		"font"			"TeamMenuTitles"
		"labelText"		"#FF_MENU_MAPGUIDE"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"mapguide"
	}

	"CancelButton"
	{
		"ControlName"	"Button"
		"fieldName"		"CancelButton"
		"xpos"			"76"
		"ypos"			"340"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#FF_MENU_CANCEL"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"cancel"
	}
}